fullnameOverride: "worker"

replicas: 1

image:
  name: ghcr.io/penxle/api

resources:
  requests:
    cpu: 1000m
    memory: 1Gi
  limits:
    memory: 2Gi

env:
  - name: PUBLIC_ENVIRONMENT
    value: "dev"

secrets:
  - worker-aws
  - worker-doppler
