nameOverride: ""
fullnameOverride: ""

replicas: 1

image:
  name: ""
  version: latest

resources:
  cpu: "100m"
  memory: "128Mi"

env: []

secrets: []

livenessProbe:
  timeoutSeconds: 1
  periodSeconds: 10
  failureThreshold: 6

readinessProbe:
  timeoutSeconds: 1
  periodSeconds: 10
  failureThreshold: 3

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

pdb:
  enabled: false
  minAvailable: "50%"
