fullnameOverride: "website"

replicas: 1

image:
  name: ghcr.io/penxle/website

resources:
  cpu: 1000m
  memory: 2Gi

env:
  - name: PUBLIC_ENVIRONMENT
    value: "dev"

secrets:
  - website-doppler

command: ["bun", "--inspect=127.0.0.1:9229", "run", "dist/index.js"]