fullnameOverride: "website"

image:
  name: ghcr.io/penxle/website

resources:
  cpu: 1000m
  memory: 4Gi

env:
  - name: PUBLIC_ENVIRONMENT
    value: "prod"

secrets:
  - website-doppler

hpa:
  enabled: true
  minReplicas: 4
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80

pdb:
  enabled: true
  minAvailable: "50%"

command: ["bun", "--inspect=127.0.0.1:9229", "run", "--cwd", "apps/website", "dist/index.js"]