fullnameOverride: "worker"

image:
  name: ghcr.io/penxle/api

resources:
  requests:
    cpu: 1000m
    memory: 2Gi
  limits:
    memory: 4Gi

livenessProbe:
  enabled: false

readinessProbe:
  timeoutSeconds: 5
  periodSeconds: 15
  failureThreshold: 3

env:
  - name: PUBLIC_ENVIRONMENT
    value: "prod"

secrets:
  - worker-aws
  - worker-doppler

hpa:
  enabled: true
  minReplicas: 4
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80

pdb:
  enabled: true
  minAvailable: "50%"
