apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
          imagePullPolicy: IfNotPresent
          {{- with .Values.command }}
          command: {{ toJson . }}
          {{- end }}
          env:
            - name: LISTEN_PORT
              value: "3000"
            - name: AWS_REGION
              value: "ap-northeast-2"
            - name: HOST_IP
              valueFrom:
                fieldRef:
                    fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(HOST_IP):4317"
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.secrets }}
          envFrom:
            {{- range .Values.secrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          {{- end }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            {{- with .Values.resources.limits }}
            limits:
              {{- with .cpu }}
              cpu: {{ . }}
              {{- end }}
              memory: {{ .memory }}
            {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz/liveness
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: 1
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /healthz/readiness
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: 1
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "app.selectorLabels" . | nindent 14 }}
  strategy:
    blueGreen:
      activeService: {{ include "app.fullname" . }}
