apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/component: database
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - chart: cloudnative-pg
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.27.1
      helm:
        valuesObject:
          config:
            data:
              INHERITED_ANNOTATIONS: ad.datadoghq.com/*

    - chart: plugin-barman-cloud
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.5.0

  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
